version: '20.10.22'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: game_indicators
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      REDIS_URL: redis://redis:6379/0
  db:
    image: postgres:13.0-alpine
    container_name: postgres_db3
    environment:
      POSTGRES_DB: game_indicators
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
    container_name: celery_worker
    command: celery -A game_indicators worker --loglevel=info
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DJANGO_SETTINGS_MODULE=game_indicators.settings

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command:
      - celery -A game_indicators beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DJANGO_SETTINGS_MODULE=project_name.settings
volumes:
  postgres_data: